""

load("@npm//:defs.bzl", "npm_link_all_packages")
load("@with_cfg.bzl", "original_settings")

npm_link_all_packages(name = "node_modules")

original_settings(
    name = "ts_project_original_settings"
)
